[versions]
fabricApi = "0.141.2+26.1" # https://fabricmc.net/develop/
fabricKotlin = "1.13.8+kotlin.2.3.0" # https://github.com/FabricMC/fabric-language-kotlin/releases
fabricLoader = "0.18.4" # https://fabricmc.net/develop/
fabricLoom = "1.14-SNAPSHOT" # https://fabricmc.net/develop/
kotlin = "2.3.0"
kotlinLogging = "7.0.3"
minecraft = "26.1-snapshot-2"
neoForgeGradle = "2.0.137" # https://projects.neoforged.net/neoforged/moddevgradle
neoForge = "26.1.0.0-alpha.5+snapshot-2" # https://projects.neoforged.net/neoforged/neoforge
neoForm = "26.1-snapshot-2-1" # https://projects.neoforged.net/neoforged/neoform

[libraries]
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricApi" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabricKotlin" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlinLogging" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

kotlin-gradlePlugin = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
neoForge-modDevGradlePlugin = { group = "net.neoforged.moddev", name = "net.neoforged.moddev.gradle.plugin", version.ref = "neoForgeGradle" }
fabric-loomGradlePlugin = { group = "net.fabricmc.fabric-loom", name = "net.fabricmc.fabric-loom.gradle.plugin", version.ref = "fabricLoom" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
neoGradle = { id = "net.neoforged.moddev", version.ref = "neoForgeGradle" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabricLoom" }

orbital-runtime = { id = "gay.pyrrha.orbital.runtime" }
orbital-shared = { id = "gay.pyrrha.orbital.shared" }
